/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-container': '#091d2f',
        'secondary-container': '#c4e9f4',
        'surface-variant': '#e1e3e4',
        background: '#f8fafb',
        'on-primary-fixed-variant': '#36485c',
        'inverse-on-surface': '#eff1f2',
        secondary: '#41636d',
        'on-tertiary-fixed': '#211b00',
        'inverse-primary': '#b6c8e0',
        'surface-tint': '#4e6075',
        'surface-container-lowest': '#ffffff',
        'on-background': '#191c1d',
        'surface-container': '#eceeef',
        'on-secondary': '#ffffff',
        'ink-black': '#02080D',
        'surface-dim': '#d8dadb',
        'primary-fixed': '#d1e4fd',
        'on-primary': '#ffffff',
        surface: '#f8fafb',
        tertiary: '#6d5e00',
        'on-tertiary-fixed-variant': '#524700',
        'surface-container-high': '#e6e8e9',
        'inverse-surface': '#2e3132',
        'on-error-container': '#93000a',
        'surface-bright': '#f8fafb',
        'on-secondary-fixed-variant': '#294c55',
        'on-surface-variant': '#43474c',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#a8ccd7',
        'on-primary-container': '#73859c',
        'tertiary-container': '#c2ab23',
        'on-tertiary': '#ffffff',
        'golden-accent': '#E8CF47',
        'primary-fixed-dim': '#b6c8e0',
        primary: '#000000',
        'surface-container-low': '#f2f4f5',
        'deep-navy': '#061A2C',
        'secondary-fixed': '#c4e9f4',
        'on-primary-fixed': '#091d2f',
        'on-secondary-container': '#476a73',
        'slate-gray': '#4A5568',
        'on-secondary-fixed': '#001f26',
        'on-surface': '#191c1d',
        'tertiary-fixed': '#fde359',
        'outline-variant': '#c4c6cd',
        'arctic-blue': '#ACD0DB',
        'surface-container-highest': '#e1e3e4',
        'tertiary-fixed-dim': '#dfc73f',
        'on-tertiary-container': '#493f00',
        'on-error': '#ffffff',
        outline: '#74777d',
        error: '#ba1a1a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max-width': '1280px',
        base: '8px',
        'section-gap': '120px',
        gutter: '24px',
        'margin-mobile': '20px',
        'margin-desktop': '80px',
      },
      maxWidth: {
        'container-max-width': '1280px',
      },
      fontFamily: {
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-xl': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'headline-xl-mobile': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-xl-mobile': ['36px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
